version: Build {build}
build_script:
- cd Build/Binary
- generate.Reflector.AIO.bat
- generate.Reflector.bat
- generate.ILSpy.AIO.bat
- generate.ILSpy.bat

artifacts:
- path: Build/Binary/reflexil.for.Reflector.$(REFLEXIL_VERSION).AIO.bin.zip
  name: Reflexil for Reflector $(REFLEXIL_VERSION) AIO Nightly
- path: Build/Binary/reflexil.for.Reflector.$(REFLEXIL_VERSION).bin.zip
  name: Reflexil for Reflector $(REFLEXIL_VERSION) Nightly
- path: Build/Binary/reflexil.for.ILSpy.$(REFLEXIL_VERSION).AIO.bin.zip
  name: Reflexil for ILSpy $(REFLEXIL_VERSION) AIO Nightly
- path: Build/Binary/reflexil.for.ILSpy.$(REFLEXIL_VERSION).bin.zip
  name: Reflexil for ILSpy $(REFLEXIL_VERSION) Nightly
  