# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: Prepare environment
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[task.setvariable variable=PATH;]${env:PATH};C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
      
- task: BatchScript@1
  displayName: Build Reflexil for Reflector AIO
  inputs:
    filename: 'Build/Binary/generate.Reflector.AIO.bat'
    workingFolder: 'Build/Binary'

- task: BatchScript@1
  displayName: Build Reflexil for Reflector
  inputs:
    filename: 'Build/Binary/generate.Reflector.bat'
    workingFolder: 'Build/Binary'

- task: BatchScript@1
  displayName: Build Reflexil for ILSpy AIO
  inputs:
    filename: 'Build/Binary/generate.ILSpy.AIO.bat'
    workingFolder: 'Build/Binary'

- task: BatchScript@1
  displayName: Build Reflexil for ILSpy
  inputs:
    filename: 'Build/Binary/generate.ILSpy.bat'
    workingFolder: 'Build/Binary'

- task: BatchScript@1
  displayName: Build Reflexil for JustDecompile AIO
  inputs:
    filename: 'Build/Binary/generate.JustDecompile.AIO.bat'
    workingFolder: 'Build/Binary'

- task: BatchScript@1
  displayName: Build Reflexil for JustDecompile
  inputs:
    filename: 'Build/Binary/generate.JustDecompile.bat'
    workingFolder: 'Build/Binary'

- task: PublishPipelineArtifact@1
  displayName: Publish Reflexil for Reflector AIO
  inputs:
    path: 'Build/Binary/reflexil.for.Reflector.*.AIO.bin.zip'
    artifact: Reflexil for Reflector AIO